// <auto-generated />
using System;
using InfnetStreaming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfnetStreaming.Data.Migrations
{
    [DbContext(typeof(InfnetStreamingDbContext))]
    partial class InfnetStreamingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Banda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFormacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Banda");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.BandaFavorita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFavoritado")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BandaFavorita");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Integrante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.ToTable("Integrante");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Musica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrdemMusica")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("Nome");

                    b.ToTable("Musica");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.MusicaFavorita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFavoritado")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MusicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MusicaFavorita");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MusicaBanda", b =>
                {
                    b.Property<Guid>("BandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BandaId", "MusicaId");

                    b.HasIndex("MusicaId");

                    b.ToTable("MusicaBanda");
                });

            modelBuilder.Entity("PlaylistMusica", b =>
                {
                    b.Property<Guid>("MusicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MusicaId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistMusica");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Album", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Banda", null)
                        .WithMany("Albuns")
                        .HasForeignKey("BandaId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.BandaFavorita", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Usuario", null)
                        .WithMany("BandasFavoritas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Genero", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Banda", null)
                        .WithMany("Generos")
                        .HasForeignKey("BandaId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Integrante", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Banda", null)
                        .WithMany("Integrantes")
                        .HasForeignKey("BandaId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Musica", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Album", null)
                        .WithMany("Musicas")
                        .HasForeignKey("AlbumId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.MusicaFavorita", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Usuario", null)
                        .WithMany("MusicasFavoritas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Usuario", null)
                        .WithMany("Playlists")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Plano", null)
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicaBanda", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Banda", null)
                        .WithMany()
                        .HasForeignKey("BandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfnetStreaming.Domain.Entities.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlaylistMusica", b =>
                {
                    b.HasOne("InfnetStreaming.Domain.Entities.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfnetStreaming.Domain.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Album", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Banda", b =>
                {
                    b.Navigation("Albuns");

                    b.Navigation("Generos");

                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("InfnetStreaming.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("BandasFavoritas");

                    b.Navigation("MusicasFavoritas");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
